# Generated by Django 4.1.3 on 2022-11-30 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photos',
            name='photo',
            field=models.FileField(upload_to='media/icon/rooms'),
        ),
    ]
