# Generated by Django 4.1.3 on 2022-11-30 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_alter_photos_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='rooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_room', models.CharField(max_length=16)),
                ('id_created', models.CharField(max_length=32)),
                ('id_icon', models.IntegerField()),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(null=True)),
                ('numHum', models.IntegerField()),
                ('max_price', models.IntegerField()),
                ('date', models.DateField()),
                ('autoRes', models.BooleanField()),
                ('private', models.BooleanField()),
                ('users', models.TextField()),
                ('OK_list', models.TextField()),
            ],
        ),
    ]
