# Generated by Django 4.1.3 on 2022-11-30 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_rooms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
