# Generated by Django 4.1.3 on 2022-12-04 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0005_alter_rooms_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='endPlay',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='listSant',
            field=models.TextField(null=True),
        ),
    ]
